name: me_landing_page
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  graphql_flutter: ^5.0.1
  flutter_dotenv: ^5.0.2
  hexcolor: ^2.0.6
  intl: ^0.17.0
  rive: ^0.8.1
  url_launcher: ^6.0.20
  visibility_detector: ^0.3.3
  flutter_staggered_animations: ^1.0.0
  google_fonts: ^3.0.1
  mixpanel_flutter: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  preload: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - .env
