name: me_landing_page
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  graphql_flutter: ^5.0.1
  flutter_dotenv: ^5.0.2
  hexcolor: ^3.0.1
  intl: ^0.18.0
  rive: ^0.10.1
  url_launcher: ^6.0.20
  visibility_detector: ^0.3.3
  flutter_staggered_animations: ^1.0.0
  google_fonts: ^4.0.3
  scrollable_positioned_list: ^0.3.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  preload: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/ 
    - .env
